services:
  api-postgrest:
    image: postgrest/postgrest
    ports:
      - 3000:3000
    depends_on:
      - database-postgres
    environment:
      - PGRST_DB_URI=postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@postgres:${DATABASE_PORT}/${DATABASE_NAME}
      - PGRST_DB_SCHEMA=${PGRST_DB_SCHEMA}
      - PGRST_DB_ANON_ROLE=${PGRST_DB_ANON_ROLE}

  database-postgres:
    image: postgres:14
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts:/scripts:ro

networks:
  your_network:
    driver: bridge

volumes:
  pgdata:
